SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [Meta].[GetClassHasHistory](@ClassID INT)
RETURNS BIT
AS
BEGIN
  RETURN (SELECT HasHistory FROM Meta.TClass WHERE ID = @ClassID);
END;
GO